In [2]:
import torch  # 导入pytorch

创建一个行向量

In [3]:
x = torch.arange(15)  # 创建0-15的行向量
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

通过张量的shape属性来访问张量（沿每个轴的长度）的形状

In [4]:
x.shape

torch.Size([15])

只想知道张量中元素的总数，即形状的所有元素乘积，可以检查它的大小（size）

In [5]:
x.numel()

15

通过x.reshape()来改变张量的形状而不改变其值
虽然张量的形状发生了改变，但其元素值并没有变。 注意，通过改变张量的形状，张量的大小不会改变。

In [6]:
X = x.reshape(3,5)   # 需重新赋值，若只是x.reshape(),则不会改变x
X

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

x.reshape()函数可指定一个参数，另一个参数用-1表示，那么-1表示的参数会自动匹配合适的参数

In [7]:
X = x.reshape(5,-1)
X

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

全0----torch.zeros()   全1----torch.ones()  正态分布----torch.randn()

In [8]:
torch.ones((3,2,3))

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [9]:
torch.zeros(5,1,5)

tensor([[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]]])

In [10]:
torch.randn(3,4)   # 每一个值都从均值为0、标准差为1的的标准正态分布中随机采样

tensor([[ 0.7841,  1.2632, -0.0188,  0.8011],
        [ 0.4200, -0.8602,  0.6061, -0.7168],
        [-0.9468,  0.4411,  0.9127, -0.6835]])

也可以通过嵌套列表对张量进行赋值

In [11]:
X = torch.tensor([[1,2,33,7],[0,0,0,0]])
X

tensor([[ 1,  2, 33,  7],
        [ 0,  0,  0,  0]])

In [12]:
X.shape

torch.Size([2, 4])

In [13]:
X.numel()

8

使用,表示一个具有5个元素的元组，每个元素都是按元素操作的结果

In [14]:
x = torch.tensor([1,2,3,4])
y = torch.tensor([0.1,0.2,0.3,0.4])

x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([1.1000, 2.2000, 3.3000, 4.4000]),
 tensor([0.9000, 1.8000, 2.7000, 3.6000]),
 tensor([0.1000, 0.4000, 0.9000, 1.6000]),
 tensor([10., 10., 10., 10.]),
 tensor([1.0000, 1.1487, 1.3904, 1.7411]))

In [15]:
# 幂运算
torch.exp(x)

tensor([ 2.7183,  7.3891, 20.0855, 54.5981])

可以把多个张量连结（concatenate）在一起， 把它们端对端地叠起来形成一个更大的张量。 我们只需要提供张量列表，并给出沿哪个轴连结。

In [16]:
x = torch.arange(12, dtype= torch.float).reshape(3,4)   # 0-14 的三行五列
y = torch.randn(12).reshape(3,4)  # 正态分布
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [17]:
torch.concat((x, y), dim=0)   # 轴--0 沿行

tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
        [ 4.0000,  5.0000,  6.0000,  7.0000],
        [ 8.0000,  9.0000, 10.0000, 11.0000],
        [-0.4679, -0.8302, -0.6785, -0.3117],
        [ 2.1225,  1.0791,  0.9164,  0.7749],
        [ 0.3561,  0.7445, -0.6844,  1.6245]])

In [18]:
torch.concat((x, y), dim=1)   # 轴--1 沿列

tensor([[ 0.0000,  1.0000,  2.0000,  3.0000, -0.4679, -0.8302, -0.6785, -0.3117],
        [ 4.0000,  5.0000,  6.0000,  7.0000,  2.1225,  1.0791,  0.9164,  0.7749],
        [ 8.0000,  9.0000, 10.0000, 11.0000,  0.3561,  0.7445, -0.6844,  1.6245]])

X == Y : 对于每个位置，如果X和Y在该位置相等，则新张量中相应项的值为1。

In [19]:
x == y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

对张量中的所有元素进行求和，会产生一个单元素张量。X.sum()

`广播机制`（broadcasting mechanism）：可以对形状不同的两个张量执行按元素操作
1. 首先通过适当复制元素来扩展一个或两个数组，使两个张量具有相同的形状
2. 然后对生成的数组执行按元素操作

In [20]:
a = torch.arange(3).reshape(3, 1)
b = torch.tensor([1,2,3])
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([1, 2, 3]))

In [21]:
a + b     # a 复制列  b 复制行

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [22]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [23]:
X[1], X[:2], X[1][:3]

(tensor([4., 5., 6., 7.]),
 tensor([[0., 1., 2., 3.],
         [4., 5., 6., 7.]]),
 tensor([4., 5., 6.]))

In [24]:
X[:2, :2] = 1000 # 前面是行， 后面是列
X

tensor([[1000., 1000.,    2.,    3.],
        [1000., 1000.,    6.,    7.],
        [   8.,    9.,   10.,   11.]])

In [25]:
before = id(a)
a = a + b
id(a) == before, id(a), before

(False, 1987987837312, 1987987826624)

In [26]:
a = torch.tensor([1,2,3])
a = torch.tensor([1,2,3]).reshape(1,-1)  # (1, 3) -1 自动选择合适的参数
c = torch.zeros_like(b)
print('id(Z):', id(c))
c[:] = a + b
print('id(Z):', id(c))

id(Z): 1987987828304
id(Z): 1987987828304


使用`X[:] = X + Y`或`X[:] = X + Y`也可以哦

In [27]:
a = torch.tensor([1,2,3])
b = torch.arange(2,5)
before = id(a)
a += b
id(a) == before

True

torch张量和numpy数组将共享它们的底层内存，就地操作更改一个张量也会**同时更改**另一个张量。

A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

使用`item`函数或者Python的内置函数可以将**大小为1**的张量转换为Python标量

In [28]:
a = torch.tensor([1.2525])
a, a.item(), int(a), float(a)

(tensor([1.2525]), 1.252500057220459, 1, 1.252500057220459)

In [29]:
import os

os.makedirs(os.path.join('..', 'data'), exist_ok=True)
data_file = os.path.join('..', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [30]:
import pandas as pd
data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


`NaN`项代表**缺失值**，有两种方法处理缺失值：

In [31]:
inputs, outputs = data.iloc[:, :2], data.iloc[:,2]  # 每一行的前两列   每一行的第3列
inputs, outputs

(   NumRooms Alley
 0       NaN  Pave
 1       2.0   NaN
 2       4.0   NaN
 3       NaN   NaN,
 0    127500
 1    106000
 2    178100
 3    140000
 Name: Price, dtype: int64)

In [32]:
inputs = inputs.fillna(inputs.mean())  # 用inputs的 同一列 的平均值 填充
inputs

C:\Users\WMGray\AppData\Local\Temp\ipykernel_19744\3649263778.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  inputs = inputs.fillna(inputs.mean())  # 用inputs的 同一列 的平均值 填充


NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN

将`NaN`当作一个类别，第二列这个`Alley`按其值分为两列。一列为1，一列为0

In [33]:
inputs = pd.get_dummies(inputs, dummy_na=True)
inputs

NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1

In [34]:
x, y = torch.tensor(inputs.values), torch.tensor(outputs.values)  # values这个属性是将ndarray的每一列作为一个列表
x, y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

In [35]:
# 删除缺失值最多的列
num = inputs.isna().sum() # 统计每一列的NaN的个数 返回类型为pd,cores.series
Max_nan = num.idxmax()  # 返回列最大值的行索引  当参数为1时返回列最大值的行索引   最小值为idxmin()
Max_nan

'NumRooms'

In [36]:
inputs.drop(labels=Max_nan, axis=1, inplace=True)  # axis 默认为0 删除行   为1时 删除列   inplace=True 修改原数据  False不改变源数据，而是新拷贝一个再修改
inputs

Alley_Pave  Alley_nan
0           1          0
1           0          1
2           0          1
3           0          1

In [37]:
x = torch.tensor(2.0)
y = torch.tensor(30.0)
x + y, x - y, x / y, x * y

(tensor(32.), tensor(-28.), tensor(0.0667), tensor(60.))

In [38]:
x = torch.arange(5)
x[2]

tensor(2)

In [39]:
len(x), x.shape

(5, torch.Size([5]))

In [40]:
A = torch.arange(10).reshape(2, -1)
A, A[1][2], A.T

(tensor([[0, 1, 2, 3, 4],
         [5, 6, 7, 8, 9]]),
 tensor(7),
 tensor([[0, 5],
         [1, 6],
         [2, 7],
         [3, 8],
         [4, 9]]))

In [41]:
B = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
B, B.T , B == B.T

(tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[1, 2, 3],
         [2, 0, 4],
         [3, 4, 5]]),
 tensor([[True, True, True],
         [True, True, True],
         [True, True, True]]))

给定具有相同形状的任意两个张量，任何按元素二元运算的结果都将是相同形状的张量。

In [42]:
A = torch.arange(20, dtype=torch.float32).reshape(5, 4)
B = A.clone()  # 通过分配新内存，将A的一个副本分配给B
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

`Hadamard积`(Hadamard product)：两个矩阵的按元素乘法（数学符号⊙）

In [43]:
A, B , A * B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[  0.,   1.,   4.,   9.],
         [ 16.,  25.,  36.,  49.],
         [ 64.,  81., 100., 121.],
         [144., 169., 196., 225.],
         [256., 289., 324., 361.]]))

将张量乘以或加上一个标量不会改变张量的形状，其中张量的每个元素都将与标量相加或相乘。

In [44]:
A = torch.tensor([[1.0,2.0],[3.0,4.0]])
B = 10
A, B, A * B, A + B

(tensor([[1., 2.],
         [3., 4.]]),
 10,
 tensor([[10., 20.],
         [30., 40.]]),
 tensor([[11., 12.],
         [13., 14.]]))

- 参数`axis=0`：按**行**元素降维，实质是求列元素的和
- 参数`axis=1：按**列**元素降维，实质求行元素的和

In [45]:
A, A.sum(), A.sum(axis=0), A.sum(axis=1)

(tensor([[1., 2.],
         [3., 4.]]),
 tensor(10.),
 tensor([4., 6.]),
 tensor([3., 7.]))

`平均值`：`mean()`函数、或者`A.sum()/A.numel()`

In [46]:
A, A.mean(), A.sum() / A.numel()

(tensor([[1., 2.],
         [3., 4.]]),
 tensor(2.5000),
 tensor(2.5000))

A.mean() 同样可以指定轴 axis=0--沿行元素 得列均值； axis=1--沿列元素 得行均值

In [47]:
A, A.mean(axis=0), A.mean(axis=1)

(tensor([[1., 2.],
         [3., 4.]]),
 tensor([2., 3.]),
 tensor([1.5000, 3.5000]))

`keepdims=True`，`sum()`函数中的参数，求和但保持**维度不变**

In [48]:
A, A.sum(axis=1, keepdim=True)

(tensor([[1., 2.],
         [3., 4.]]),
 tensor([[3.],
         [7.]]))

沿某个轴计算`A`元素的累积总和----`cunsum()`函数，不降低维度

In [49]:
A = torch.tensor([[1,2],[3,4],[5,6],[7,8]])
A, A.cumsum(axis=0)

(tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]),
 tensor([[ 1,  2],
         [ 4,  6],
         [ 9, 12],
         [16, 20]]))

点积：相同位置元素乘积的和

In [50]:
x = torch.tensor([1,2,3,4])
y = torch.arange(4)
x, y, torch.dot(x,y), torch.sum(x * y)

(tensor([1, 2, 3, 4]), tensor([0, 1, 2, 3]), tensor(20), tensor(20))

矩阵向量积--mv()

In [51]:
x = torch.tensor([1,2])
A, x, A.shape, x.shape, torch.mv(A,x)

(tensor([[1, 2],
         [3, 4],
         [5, 6],
         [7, 8]]),
 tensor([1, 2]),
 torch.Size([4, 2]),
 torch.Size([2]),
 tensor([ 5, 11, 17, 23]))

L2范数：向量元素平方和的平方根

In [58]:
u = torch.tensor([3.0,-4.0])   # 浮点型
torch.norm(u)

tensor(5.)

L1范数：向量元素的绝对值之和

In [59]:
torch.abs(u).sum()

tensor(7.)

矩阵范数：矩阵元素平方和的平方根

In [61]:
torch.ones((4, 9)), torch.norm(torch.ones((4, 9)))

(tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1., 1., 1., 1.]]),
 tensor(6.))