In [1]:
import torch  # 导入pytorch

创建一个行向量

In [2]:
x = torch.arange(15)  # 创建0-15的行向量
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

通过张量的shape属性来访问张量（沿每个轴的长度）的形状

In [4]:
x.shape

torch.Size([15])

只想知道张量中元素的总数，即形状的所有元素乘积，可以检查它的大小（size）

In [6]:
x.numel()

15

通过x.reshape()来改变张量的形状而不改变其值
虽然张量的形状发生了改变，但其元素值并没有变。 注意，通过改变张量的形状，张量的大小不会改变。

In [15]:
X = x.reshape(3,5)   # 需重新赋值，若只是x.reshape(),则不会改变x
X

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]])

x.reshape()函数可指定一个参数，另一个参数用-1表示，那么-1表示的参数会自动匹配合适的参数

In [17]:
X = x.reshape(5,-1)
X

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11],
        [12, 13, 14]])

全0----torch.zeros()   全1----torch.ones()  正态分布----torch.randn()

In [19]:
torch.ones((3,2,3))

tensor([[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]])

In [21]:
torch.zeros(5,1,5)

tensor([[[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.]]])

In [22]:
torch.randn(3,4)   # 每一个值都从均值为0、标准差为1的的标准正态分布中随机采样

tensor([[-0.4074,  0.7035, -0.8163,  0.3031],
        [-0.4960, -0.2129, -0.0820, -0.2760],
        [-0.4858,  0.1528,  1.1781,  0.4026]])

也可以通过嵌套列表对张量进行赋值

In [28]:
X = torch.tensor([[1,2,33,7],[0,0,0,0]])
X

tensor([[ 1,  2, 33,  7],
        [ 0,  0,  0,  0]])

In [31]:
X.shape

torch.Size([2, 4])

In [32]:
X.numel()

8

使用,表示一个具有5个元素的元组，每个元素都是按元素操作的结果

In [34]:
x = torch.tensor([1,2,3,4])
y = torch.tensor([0.1,0.2,0.3,0.4])

x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([1.1000, 2.2000, 3.3000, 4.4000]),
 tensor([0.9000, 1.8000, 2.7000, 3.6000]),
 tensor([0.1000, 0.4000, 0.9000, 1.6000]),
 tensor([10., 10., 10., 10.]),
 tensor([1.0000, 1.1487, 1.3904, 1.7411]))

In [35]:
# 幂运算
torch.exp(x)

tensor([ 2.7183,  7.3891, 20.0855, 54.5981])

可以把多个张量连结（concatenate）在一起， 把它们端对端地叠起来形成一个更大的张量。 我们只需要提供张量列表，并给出沿哪个轴连结。

In [46]:
x = torch.arange(12, dtype= torch.float).reshape(3,4)   # 0-14 的三行五列
y = torch.randn(12).reshape(3,4)  # 正态分布
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [47]:
torch.concat((x, y), dim=0)   # 轴--0 沿行

tensor([[ 0.0000,  1.0000,  2.0000,  3.0000],
        [ 4.0000,  5.0000,  6.0000,  7.0000],
        [ 8.0000,  9.0000, 10.0000, 11.0000],
        [-0.6631,  0.1505,  1.8609, -0.5190],
        [ 1.7616,  1.5391,  0.6745,  1.3089],
        [ 0.0741, -1.7690, -0.8764, -0.9673]])

In [48]:
torch.concat((x, y), dim=1)   # 轴--1 沿列

tensor([[ 0.0000,  1.0000,  2.0000,  3.0000, -0.6631,  0.1505,  1.8609, -0.5190],
        [ 4.0000,  5.0000,  6.0000,  7.0000,  1.7616,  1.5391,  0.6745,  1.3089],
        [ 8.0000,  9.0000, 10.0000, 11.0000,  0.0741, -1.7690, -0.8764, -0.9673]])

X == Y : 对于每个位置，如果X和Y在该位置相等，则新张量中相应项的值为1。

In [49]:
x == y

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

对张量中的所有元素进行求和，会产生一个单元素张量。

`广播机制`（broadcasting mechanism）：可以对形状不同的两个张量执行按元素操作
1. 首先通过适当复制元素来扩展一个或两个数组，使两个张量具有相同的形状
2. 然后对生成的数组执行按元素操作

In [53]:
a = torch.arange(3).reshape(3, 1)
b = torch.tensor([1,2,3])
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([1, 2, 3]))

In [54]:
a + b     # a 复制列  b 复制行

tensor([[1, 2, 3],
        [2, 3, 4],
        [3, 4, 5]])

In [60]:
x[0][:2]

tensor([0., 1.])

In [61]:
x

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])